export const CENTRAL_PAGE_ID = 'project-workorder';

export const pages = [
  {
    id: 'customer-admission',
    title: '客户准入页',
    navTitle: '客户准入',
    phase: '客户准入',
    priority: 'P0',
    status: '可推进',
    objective: '筛选适合进入 TikTok 增长服务流程的品牌型卖家。',
    objects: ['客户', '客户状态', '商机评分与标签'],
    nextAction: '发起启动前检查',
  },
  {
    id: 'launch-checklist',
    title: '启动前检查页',
    navTitle: '启动前检查',
    parentId: 'customer-admission',
    hideInSidebar: true,
    pageRole: 'context-subpage',
    phase: '启动准备',
    priority: 'P1',
    status: '检查中',
    objective: '检查客户是否具备项目启动条件。',
    objects: ['启动前检查单', '店铺准备状态', '广告资产接入状态', '归因准备状态'],
    nextAction: '确认是否允许继续推进',
  },
  {
    id: 'payment-authorization',
    title: '回款账户绑定与扣款授权页',
    navTitle: '账户与扣款',
    phase: '账户授权',
    priority: 'P1',
    status: '已授权',
    objective: '完成客户回款账户绑定和自动扣款授权准备。',
    objects: ['回款账户绑定记录', '自动扣款授权记录'],
    nextAction: '进入授信审批',
  },
  {
    id: 'credit-approval',
    title: '授信审批页',
    navTitle: '授信审批',
    phase: '授信审批',
    priority: 'P0',
    status: '已通过',
    objective: '完成额度、账期、保证金和风险等级配置。',
    objects: ['授信单', '客户授信状态'],
    nextAction: '创建项目工单',
  },
  {
    id: CENTRAL_PAGE_ID,
    title: '项目工单详情页',
    navTitle: '项目工单',
    phase: '项目中枢',
    priority: 'P0',
    status: '执行中',
    isCentral: true,
    objective: '集中承接项目推进、任务分工、达人合作、素材资产、消耗、账单回款等关键信息。',
    objects: ['项目工单', '客户', '授信摘要', '执行任务', '达人合作摘要', '素材资产摘要', '消耗记录摘要', '账单摘要', '自动扣款摘要'],
    nextAction: '推进授权和小预算测试',
  },
  {
    id: 'creator-assets',
    title: '达人合作与素材资产页',
    navTitle: '达人与素材',
    phase: '内容供给',
    priority: 'P1',
    status: '待授权',
    objective: '展示达人合作漏斗，以及素材从交付物到可投资产的转化过程。',
    objects: ['达人合作单', '素材资产'],
    nextAction: '推进素材授权与测试',
  },
  {
    id: 'billing-collection',
    title: '账单回款页',
    navTitle: '账单回款',
    phase: '应收回款',
    priority: 'P0',
    status: '部分回款',
    objective: '展示应收、自动扣款、回款、核销和风险联动。',
    objects: ['账单', '回款单', '自动扣款授权信息', '风险状态'],
    nextAction: '跟进待收金额',
  },
  {
    id: 'customer-portal',
    title: '客户轻门户',
    navTitle: '客户门户',
    phase: '客户协同',
    priority: 'P1',
    status: '待确认',
    objective: '让客户低成本参与确认、查看和支付动作。',
    objects: ['客户项目摘要', '内容确认事项', '回款账户状态', '账单与支付状态'],
    nextAction: '客户确认内容与账单',
  },
];

export const workflow = [
  '客户准入',
  '启动准备',
  '账户授权',
  '授信审批',
  '项目中枢',
  '内容供给',
  '应收回款',
  '客户协同',
];
